In [ ]:
## if Use Colab
# from pycaret.utils import enable_colab
# enable_colab()

In [17]:
from pycaret.classification import *
from pycaret.regression import *
from pycaret.datasets import get_data

In [10]:
dataset = get_data('diamond')
#dataset.shape = (6000, 8)

   Carat Weight    Cut Color Clarity Polish Symmetry Report  Price
0          1.10  Ideal     H     SI1     VG       EX    GIA   5169
1          0.83  Ideal     H     VS1     ID       ID   AGSL   3470
2          0.85  Ideal     H     SI1     EX       EX    GIA   3183
3          0.91  Ideal     E     SI1     VG       VG    GIA   4370
4          0.83  Ideal     G     SI1     EX       EX    GIA   3171

In [20]:
#데이터 준비
data = dataset.sample(frac=0.9, random_state=786) 
data_unseen = dataset.drop(data.index) 
data.reset_index(drop=True, inplace=True) 
data_unseen.reset_index(drop=True, inplace=True) 
print('Data for Modeling: ' + str(data.shape)) 
print('Unseen Data For Predictions: ' + str(data_unseen.shape)) # Data for Modeling: (5400, 8) # Unseen Data For Predictions: (600, 8)

Data for Modeling: (5400, 8)
Unseen Data For Predictions: (600, 8)

In [18]:
# 모델 환경설정
exp_reg001 = setup(data = data, target = 'Price', session_id=123)

In [19]:
# 데이터에 대한 모델 추천 실행
best = compare_models(exclude=['ransac'])